name = "My Modpack"
author = "Me"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "27f94901f43df6882d8dfbd558f33c4774c2a6d5db69f8f105bdc26323b76511"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.229"
