name = "My Modpack"
author = "Me"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bd0553cd0ca7cd77ab26928670960f4bb56898c86e40d98eece2de9e54a1d0f5"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.229"
