name = "My Modpack"
author = "Me"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bd11f224bb1029e9f5289c1e841e990d0210fba90174e4f9dfad2e05a2282900"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.229"
